<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="F_Scaling" Id="{45ef72a9-5505-4f12-a785-64215dafa89f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_Scaling : REAL
VAR_INPUT
	rawInput : INT;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_Scaling := rawInput/327.67;]]></ST>
    </Implementation>
    <LineIds Name="F_Scaling">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>